### ISSUE TITLE
Moving it to OpenStack?

### ISSUE THREAD

**Issue by EmilienM** [twc-openstack/puppet-os_docker#1]
Would you be interested to move this repository under Puppet OpenStack project, using Infra gate for testing, etc.

I see a lot of interest to have a project that helps containers deployment, and having this work in the community would help both TWC & OpenStack community to have a common project to deploy OpenStack on containers using Puppet modules.
Kolla & OSA already support container deployments, why not us?

**Comment by EmilienM** [comment]
ping @dvorak @matthewfischer

**Comment by claytono** [comment]
I'm not opposed, but it would need a lot of work in order for that to happen.  We've made an effort to have it not be _completely_ opinionated, but it does make some assumptions about how the containers are constructed which probably aren't true for everyone.

**Comment by matthewfischer** [comment]
Also not opposed but would like to discuss in Austin. I don't want to end up with something that we have to re-fork because it won't work for us and need to balance that with a general solution.
